title: "Ch0p5h0p"
tagline: "My Homepage"
description: "My Homepage"
github_username: Ch0p5h0p
baseurl: "/"
url: "https://Ch0p5h0p.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - portfolio.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
